<?php

require 'vendor/autoload.php';

use Convenia\Dominio\EmployeeExport\EmployeeExport;

$dominio = new EmployeeExport;

$employees = [
    [
        'nacionalidade' => 30,
        'codi_emp' => 2,
        'horas_semana' => 40,
        'admissao' => '17/07/2017',
        'horas_mes' => 200,
        'data_nascimento' => '05/10/1990',
        'venc_ferias' => '16/07/2018',
        'i_depto' => 2,
        'sai_rais' => 'S',
        'DESCONTAR_CONTRIBUICAO_SINDICAL_A_PARTIR_11_2017' => 0,
        'cor' => 2,
        'i_filiais' => 1,
        'paga_contr_sind' => 'S',
        'PAGA_CONTR_SIND_11_2017' => 'S',
        'salario' => '4000',
        'vinculo' => 1,
        'ORGAO_EXPEDICAO_RG' => 'SSP',
        'grau_instrucao' => 9,
        'sexo' => 'M',
        'emprego_ant' => 1,
        'i_ccustos' => 3,
        'categoria' => 1,
        'forma_pagto' => 'D',
        'nome' => 'FUNCIONARIO TESTE',
        'opta_fgts' => 'S',
        'possui_vinc_out_emp' => 'N',
        'horas_dia' => '6.66',
        'POSSUI_DEFICIENCIA_INTELECTUAL' => 0,
        'i_servicos' => 1,
        'cpf' => '15794232056',
        'pis' => '93065591046',
        'i_cargos' => 1,
        'i_sindicatos' => 21,
        'cart_prof' => '12345678910',
        'dt_exp_ident' => '10/10/2010',
        'serie_cart_prof' => 12345,
        'I_JORNADA' => 1,
        'endereco' => 'Rua da Copa',
        'PAIS_NACIONALIDADE' => 30,
        'MUNICIPIO_NASCIMENTO' => 5345,
        'TIPO_INSCRICAO_EMPRESA_ORIGEM_DIRIGENTE_SINDICAL' => 1,
        'TIPO_INDICATIVO_ADMISSAO' => 1,

        // TESTE

        'EXCLUIR_EVENTO_S_2205_RETIFICACAO' => 0,
        'IMOVEL_ADQUIRIDO_RECURSOS_FGTS' => 0,
        'usa_sist' => 0,
        'INCLUSAO_VALIDADA_ESOCIAL_S_2205' => 0,
        'EMPRESA_ORIGEM_DESONERADA' => 0,
        'DIRIGENTE_SINDICAL' => 0,
        'BRASILEIRO_NASCIDO_EXTERIOR' => 0,
        'OPCAO_PLANO_SAUDE' => 0,
        'ENVIAR_ESOCIAL' => 0,
        'BENEFICIADO_PAT_ALIMENTACAO_CONVENIO' => 0,
        'DESCONTAR_CONTRIBUICAO_SINDICAL_A_PARTIR_11_2017' => 0,
        'GERAR_RETIFICACAO_ESOCIAL_S_2205' => 0,
        'tipo_contrib' => 0,
        'CALCULAR_ADIANTAMENTO_SALARIAL' => 0,
        'BENEFICIADO_PAT' => 0,
        'origem_reg' => 0,
        'gps_trimestral' => 0,
        'ENVIAR_S_2200_REINTEGRACAO' => 0,
        'contrib_indiv' => 0,
        'RECEBIA_SEGURO_DESEMPREGO' => 0,
        'INCLUSAO_VALIDADA_ESOCIAL' => 0,
        'I_AFASTAMENTOS' => 0,
        'CALCULAR_INSS_PATRONAL' => 0,
        'INCLUSAO_VALIDADA_ESOCIAL_S_2206' => 0,
        'BENEFICIADO_PAT_REFEICAO_CONVENIO' => 0,
        'RESIDENCIA_PROPRIA' => 0,
        'deficiente_fisico' => 0,
        'ENDERECO_COMERCIAL' => 0,
        'ENVIAR_ESOCIAL_S_2205' => 0,
        'ENVIAR_ESOCIAL_S_2206' => 0,
        'SITUACAO_QUALIFICACAO_CADASTRAL_INSS_RECEITA_FEDERAL' => 0,
        'BENEFICIADO_PAT_REFEICOES_TRANSPORTADAS' => 0,
        'emprego_ant' => 0,
        'tempermuta' => 0,
        'DESLIGAMENTO_ENVIADO_ESOCIAL_REINTEGRACAO' => 0,
        'DESLIGAMENTO_REALIZADO_MESMO_BANCO_REINTEGRACAO' => 0,
        'EXCLUIR_EVENTO_S_2206_RETIFICACAO' => 0,
        'USA_SALARIO_MINIMO_ESTADUAL' => 0,
        'categoria' => 0,
        'forma_pagto' => 0,
        'BENEFICIADO_PAT_ADMINISTRACAO_COZINHAS' => 0,
        'i_empregados' => 100000,
        'GERAR_RETIFICACAO_ESOCIAL_S_2206' => 0,
        'CARGA_HORARIA_VARIAVEL' => 0,
        'DESCONTAR_ESTOURO_RESCISAO_EMPRESA_ORIGEM' => 0,
        'GERAR_RETIFICACAO_ESOCIAL' => 0,
        'contr_sobre_sal_min' => 0,
        'BENEFICIADO_PAT_CESTA_ALIMENTOS' => 0,
        'RESIDENTE_EXTERIOR' => 0,
        'ALVARA_JUDICIAL' => 0,
        'POSSUI_REDUCAO_ALIQUOTA_INSS' => 0,
        'gps_deducao' => 0,
        'tipo_epr' => 0,
        'troca_aut_clas' => 0,
        'ENVIAR_REGISTRO_APOS_EXCLUSAO_ESOCIAL' => 0,
        'BENEFICIADO_PAT_SERVICO_PROPRIO' => 0,
        'possui_vinc_out_emp' => 0,
        'simples_072007' => 123,
        'REMUNERACAO_PERIODO_DESLIGAMENTO_REINTEGRACAO_PAGAS_JUIZO' => 0,
        'TRANSFERIDO_COM_EMPREGADO_ORIGEM_VALIDADO_NO_ESOCIAL' => 0,
        'COTA_DIFICIENTE' => 0,
        'GPS_CONJUNTA_NOVEMBRO_13_INTEGRAL' => 0,
    ]
];

echo $dominio->employees($employees)->generate();